name: Build jcudax-natives-windows-x86_64

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # Step 1: 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: 设置 JDK 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      # Step 3: 安装Visual Studio 2022
      - name: Install Visual Studio 2022
        uses: microsoft/setup-msbuild@v1.0
        with:
          vs-version: '2022'

      # Step 4: 安装 CUDA 工具链
      - name: Set up CUDA 12.0.0 and cuDNN on Windows
        run: |
          choco install cuda --version=12.0
          # Install cuDNN (Ensure you have a valid NVIDIA Developer account to access cuDNN)
          choco install cudnn --version=8.7.0.84

      # Step 4: 编译c语言代码
      - name: Compile CUDA code on Windows
        run: |
            # This step ensures that nvcc is using MSVC from Visual Studio 2022
            nvcc -O3 -arch=sm_90 -shared -o jcudax-natives-12.0.0/src/main/resources/JCudax-12.0.0-windows-x86_64.dll jcudax-natives-12.0.0/src/main/c/JCudax.cu
